In [3]:
#Numpu tutorial

In [15]:
list1 = [1, 2, 3, 4]
res=[]
for x in list1:
    res.append(x*2)
print(res)

[2, 4, 6, 8]


In [17]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr*2)

[2 4 6 8]


In [19]:
import numpy as np
print(np.__version__)

1.26.4


In [21]:
import numpy as np
a=np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [23]:
print(a.ndim)

1


In [27]:
b=np.array([[1,2,3],[4,5,6]])
print(b)
print(b.ndim)
print(b.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [11]:
c=np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
print(c.ndim)

3


In [19]:
import numpy as np
arr1=np.array([23,4,5,566])
print(arr1)
print(arr1.ndim)

[ 23   4   5 566]
1


In [31]:
import numpy as np
arr2=np.array([[23,4,5,566],[235,57,456,45]])
print(arr2)
print(arr2.ndim)

[[ 23   4   5 566]
 [235  57 456  45]]
2


In [32]:
import numpy as np
arr3=np.array([[[23,4,5,566],[235,57,456,45]]])
print(arr3)
print(arr3.ndim)

[[[ 23   4   5 566]
  [235  57 456  45]]]
3


In [39]:
print(arr3.size) #total elements count

8


In [41]:
print(arr3.dtype) # Data type of elements

int32


In [43]:
print(arr3.shape)  # Shape (rows, columns, etc.)

(1, 2, 4)


In [59]:
import numpy as np

arr = np.array([10, 20, 30, 40])
print(arr[0])

10


In [61]:
print(arr[2])

30


In [63]:
print(arr[-1])

40


In [71]:
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(arr2[1,0])

4


In [83]:
import numpy as np
arr4=np.array([[[43,6,78],[44,67,74],
               [43,6,78],[44,67,74]
               ]])
print(arr4.ndim)
print(arr4.shape)

3
(1, 4, 3)


In [87]:
import numpy as np
arr_1=np.array([34,67,34,32])
print(arr_1[2])

34


In [89]:
arr_1[2]=108
print(arr_1)

[ 34  67 108  32]


In [93]:
print(arr_1[::-1])

[ 32 108  67  34]


In [ ]:
# reshape()

In [97]:
import numpy as np
arr=np.array([45,567,45,3])
print("Origianl shape:",arr.shape) #there are 4 elements so we get (4,)

Origianl shape: (4,)


In [105]:
import numpy as np
arr2=np.array([[45,567,45,3],
               [46,23,3,23]])
print("Origianl shape:",arr2.shape) #here we will get output as (2,4) because there are 2 rows, and 4 total columns

Origianl shape: (2, 4)


In [111]:
import numpy as np
arr=np.array([34,4,78,7,546,32])
new_arr=arr.reshape(2,3)
print(new_arr)
print(new_arr.ndim)

[[ 34   4  78]
 [  7 546  32]]
2


In [114]:
#activity

In [117]:
import numpy as np
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])


In [ ]:
# Question 1:
# Display the last column →
# We need all rows (:) but only last column (-1).
# If you want it as a 2D column, keep the second index as -1: or [-1:].

In [127]:
print(arr2d[:,-1:])

[[3]
 [6]
 [9]]


In [133]:
import numpy as np

arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print(arr2d[1,1:])


[5 6]


In [135]:
arr2d = np.array([[10, 20, 30, 40],
                  [50, 60, 70, 80],
                  [90, 100, 110, 120]])


In [137]:
print(arr2d[0,1:3])

[20 30]


In [139]:
# Notes for exam

In [ ]:
# 📌 NumPy Exam Notes
# 1. What is NumPy?
# NumPy = Numerical Python.

# Used for fast numerical calculations in Python.

# Works with n-dimensional arrays.

In [147]:
# # 2. Creating Arrays
# import numpy as np

# # From Python list
# arr = np.array([1, 2, 3])         # 1D
# arr2 = np.array([[1, 2], [3, 4]]) # 2D

# # Predefined functions
# np.zeros((2,3))   # 2x3 array of 0s
# np.ones((3,3))    # 3x3 array of 1s
# np.full((2,2), 5) # 2x2 filled with 5
# np.eye(3)         # Identity matrix
# np.arange(1, 10, 2) # 1 to 9 step 2
# np.linspace(0, 1, 5) # 5 equally spaced numbers from 0 to 1


In [149]:
# # 3. Array Attributes
# arr.shape   # Dimensions (rows, cols)
# arr.ndim    # Number of dimensions
# arr.size    # Total elements
# arr.dtype   # Data type


In [ ]:
# 4. Indexing & Slicing
# arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

# arr[0,0]       # 1 (1st row, 1st col)
# arr[1]         # [4,5,6] (2nd row)
# arr[:, 1]      # [2,5,8] (2nd column)
# arr[:, -1]     # Last column as 1D
# arr[:, -1:]    # Last column as 2D
# arr[1, 1:3]    # [5,6] (last 2 of middle row)


In [151]:
# 5. Reshaping
# a = np.array([1,2,3,4,5,6])
# a.reshape(2,3)  # Change shape
# a.flatten()     # Convert to 1D


In [157]:
# # 6. Mathematical Operations
# a = np.array([1,2,3])
# b = np.array([4,5,6])
# a+b
# a-b
# a*b
# a/b
# np.sqrt(a)
# np.sum(a)
# np.mean(a)
# np.max(a)
# np.min(a)

1

In [ ]:
# Copy vs View
# View → changes affect original array.

# Copy → changes don’t affect original array.
# x = np.array([1,2,3])
# y = x.view()
# z = x.copy()
